# Generated by Django 5.0.1 on 2024-02-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=20)),
                ('about', models.TextField()),
                ('facebook', models.URLField()),
                ('tiktok', models.URLField()),
                ('instagram', models.URLField()),
            ],
        ),
    ]
