# Generated by Django 5.0.1 on 2024-02-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='map',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
