# Generated by Django 5.0.1 on 2024-02-19 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_agecroups_images_schedules_videos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('personal_image', models.ImageField(upload_to='images/')),
                ('cover_image', models.ImageField(upload_to='images/')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('foot', models.CharField(choices=[('R', 'მარჯვენა'), ('L', 'მარცხენა')], max_length=20)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('D', 'Defender'), ('SW', 'Sweeper'), ('CB', 'Center Back'), ('RCB', 'Right Center Back'), ('LCB', 'Left Center Back'), ('RB', 'Right Back'), ('LB', 'Left Back'), ('WB', 'Wing Back'), ('RWB', 'Right Wing Back'), ('LWB', 'Left Wing Back'), ('M', 'Midfielder'), ('MD', 'Defensive Mdfielder'), ('CDM', 'Center Defensive Midfielder'), ('CM', 'Center Midfielder'), ('RM', 'Right Midfielder'), ('LM', 'Left Midfielder'), ('AM', 'Attacking Midfielder'), ('CAM/AMC', 'Centre Attacking Midfielder'), ('AMR', 'Attacking Midfielder Right'), ('AML', 'Attacking Midfielder Left'), ('RW', 'Right Winger'), ('LW', 'Left Winger'), ('SS', 'Second Striker'), ('CF', 'Centre Forward'), ('ST', 'Striker')], max_length=50)),
                ('skill_statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.skill_statistics')),
            ],
        ),
    ]
