# Generated by Django 5.0.1 on 2024-02-28 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_skill_statistics_personalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_10', models.CharField(max_length=50, verbose_name='სისწრაფე(10 მ.)')),
                ('speed_20', models.CharField(max_length=50, verbose_name='სისწრაფე(20 მ.)')),
                ('speed_30', models.CharField(max_length=50, verbose_name='სისწრაფე(30 მ.)')),
                ('speed_50', models.CharField(max_length=50, verbose_name='სისწრაფე(50 მ.)')),
                ('speed_100', models.CharField(max_length=50, verbose_name='სისწრაფე(100 მ.)')),
                ('penal_left', models.CharField(max_length=50, verbose_name='პენალტი (მარჯვ.)')),
                ('penal_right', models.CharField(max_length=50, verbose_name='პენალტი (მარცხ.)')),
                ('kick_centre_right', models.CharField(max_length=50, verbose_name='დარტყმა( 16.5 მ (ცენტრი)) (ფეხი მარჯ.)')),
                ('kick_centre_left', models.CharField(max_length=50, verbose_name='დარტყმა( 16.5 მ (ცენტრი)) (ფეხი მარცხ.)')),
                ('kick_right_angle_foot_right', models.CharField(max_length=50, verbose_name='დარტყმა( 16.5 მ (რკალი მარცხენა)) (ფეხი მარჯ.)')),
                ('kick_right_angle_foot_left', models.CharField(max_length=50, verbose_name='დარტყმა( 16.5 მ (რკალი მარცხენა)) (ფეხი მარცხ.)')),
                ('kick_left_angle_foot_right_circl', models.CharField(max_length=50, verbose_name='დარტყმა( 16.5 მ (რკალი მარჯვენა)) (ფეხი მარჯ.)')),
                ('kick_left_angle_foot_left_circl', models.CharField(max_length=50, verbose_name=' დარტყმა( 16.5 მ (რკალი მარჯვენა)) (ფეხი მარცხ.)')),
                ('kick_right', models.CharField(max_length=50, verbose_name='ჟონგლირება (ფეხი მარჯ.)')),
                ('kick_left', models.CharField(max_length=50, verbose_name='ჟონგლირება (ფეხი მარცხ.)')),
                ('kick_head', models.CharField(max_length=50, verbose_name='ჟონგლირება (თავი)')),
                ('kick_knee_right', models.CharField(max_length=50, verbose_name='ჟონგლირება (მუხლი მარჯვ.)')),
                ('kick_knee_left', models.CharField(max_length=50, verbose_name='ჟონგლირება (მუხლი მარცხ.)')),
                ('jogging', models.CharField(max_length=50, verbose_name='ძუნძული (100 მ.)')),
                ('pass_right', models.CharField(max_length=50, verbose_name='ბალანსი, პასი (მარჯვ. შიდა ტერფი)')),
                ('pass_left', models.CharField(max_length=50, verbose_name='ბალანსი, პასი (მარცხ. შიდა ტერფი)')),
                ('pass_left_upper', models.CharField(max_length=50, verbose_name='ბალანსი, პასი (მარჯვ. ზედა ტერფი)')),
                ('pass_right_upper', models.CharField(max_length=50, verbose_name='ბალანსი, პასი (მარცხ. ზედა ტერფი)')),
            ],
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='birth_date',
            field=models.DateField(verbose_name='დაბადების თარიღი'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='სახელი'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='foot',
            field=models.CharField(choices=[('R', 'მარჯვენა'), ('L', 'მარცხენა')], max_length=20, verbose_name='ფეხი'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='height',
            field=models.FloatField(verbose_name='სიმაღლე'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='გვარი'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('D', 'Defender'), ('SW', 'Sweeper'), ('CB', 'Center Back'), ('RCB', 'Right Center Back'), ('LCB', 'Left Center Back'), ('RB', 'Right Back'), ('LB', 'Left Back'), ('WB', 'Wing Back'), ('RWB', 'Right Wing Back'), ('LWB', 'Left Wing Back'), ('M', 'Midfielder'), ('MD', 'Defensive Mdfielder'), ('CDM', 'Center Defensive Midfielder'), ('CM', 'Center Midfielder'), ('RM', 'Right Midfielder'), ('LM', 'Left Midfielder'), ('AM', 'Attacking Midfielder'), ('CAM/AMC', 'Centre Attacking Midfielder'), ('AMR', 'Attacking Midfielder Right'), ('AML', 'Attacking Midfielder Left'), ('RW', 'Right Winger'), ('LW', 'Left Winger'), ('SS', 'Second Striker'), ('CF', 'Centre Forward'), ('ST', 'Striker')], max_length=50, verbose_name='პოზიცია'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='weight',
            field=models.FloatField(verbose_name='წონა'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='skill_statistic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.skillstatistics'),
        ),
        migrations.DeleteModel(
            name='Skill_statistics',
        ),
    ]
