# Generated by Django 5.0.1 on 2024-02-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_remove_personalinfo_username_personalinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='user',
            new_name='username',
        ),
    ]
