# Generated by Django 5.0.1 on 2024-02-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_alter_personalinfo_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='username',
            new_name='user',
        ),
    ]
